name: manage-azure-policy-e65fb29a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**'
#      - .github/workflows/manage-azure-policy-e65fb29a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e65fb29a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      #uses: azure/manage-azure-policy@v0
      uses: azure/arm-deploy@v1
      with:
        #paths: |
        #  policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**
        template: policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/assign.Allowed_locations_65fc949ed1c34e36a75189d7.json
        parameters: policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/parameters.json
