name: manage-azure-cli-e65fb29a
on:
  workflow_dispatch:
    inputs:
      Remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Run azure script'
      Subscription:
        description: 'Enter Subscription Id with coma seperated'
        required: false
        #default: 'Run azure script'
      Group:  
        description: 'Enter Group Id with coma seperated'
        required: false

## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/**'
#      - .github/workflows/manage-azure-policy-e65fb29a.yml
jobs:
  run-azure-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.myApp2}}
        allow-no-subscriptions: true
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          chmod +x policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/Script.sh
          policies/Allowed_locations_e56962a6-4747-49cd-b67b-bf8b01975c4c/Script.sh ${{ inputs.Subscription }}
          
        
